version: 'utox-{build}'
clone_depth: 5

environment:
  matrix:
    - job_name: Linux
      appveyor_build_worker_image: Ubuntu2404

    - job_name: Windows x64 (cross)
      appveyor_build_worker_image: Ubuntu2404

    - job_name: Windows x64 (Cygwin)
      appveyor_build_worker_image: Visual Studio 2026
      CYG_ROOT: C:\cygwin
      CYG_CACHE: C:\cygwin\var\cache\setup
      CYG_MIRROR: http://cygwin.mirror.constant.com

matrix:
  fast_finish: false

build: off

for:
  - matrix:
      only:
        - job_name: Linux

    cache:
      - /home/appveyor/cache

    install:
      - sh: |
          set -eux
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install --no-install-recommends \
            cmake cmake-data check libdbus-1-dev libx11-dev libfreetype6-dev \
            libfontconfig1-dev libxrender-dev libxext-dev \
            libsodium-dev libopus-dev libvpx-dev \
            libopenal-dev libopenal-data libv4l-dev \
            git
          git submodule update --init --recursive

    build_script:
      - sh: |
          set -eux
          ./extra/travis/linux-before.sh
          ./extra/travis/filter_audio.sh
          ./extra/travis/linux-script.sh

  - matrix:
      only:
        - job_name: Windows x64 (cross)

    cache:
      - /home/appveyor/cache

    install:
      - sh: |
          set -eux
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install --no-install-recommends \
            cmake make gcc mingw-w64 gcc-mingw-w64 mingw-w64-common binutils-mingw-w64 \
            yasm nasm autoconf automake libtool pkg-config curl git
          git submodule update --init --recursive

    build_script:
      - sh: |
          set -eux
          sh ./extra/travis/windows.sh

  - matrix:
      only:
        - job_name: Windows x64 (Cygwin)

    cache:
      - '%CYG_CACHE%'
      - C:\cygwin\home\appveyor\cache

    install:
      - git config --global core.autocrlf input
      - git submodule update --init --recursive
      - ps: New-Item -ItemType Directory -Force -Path $env:CYG_ROOT, $env:CYG_CACHE | Out-Null
      - curl -L https://cygwin.com/setup-x86_64.exe -o %CYG_ROOT%\setup-x86_64.exe
      - '%CYG_ROOT%\setup-x86_64.exe -qgnNdO -l %CYG_CACHE% -R %CYG_ROOT% -s %CYG_MIRROR% -P mingw64-x86_64-gcc-core,mingw64-x86_64-gcc-g++,mingw64-x86_64-headers,mingw64-x86_64-windows-default-manifest,cmake,make,git,curl,autoconf,automake,libtool,pkg-config,yasm,nasm,patch,perl,file'

    build_script:
      - set CHERE_INVOKING=1
      - '%CYG_ROOT%\bin\bash.exe --login -eo pipefail -o igncr -c "cd \"$(cygpath -u \"$APPVEYOR_BUILD_FOLDER\")\" && sh ./extra/travis/windows.sh"'
