#define UTOX_DEFAULT_AUDIO_BITRATE 32
#define UTOX_DEFAULT_AUDIO_FRAME_DURATION 20
#define UTOX_DEFAULT_AUDIO_SAMPLE_RATE 48000
#define UTOX_DEFAULT_AUDIO_CHANNELS 1



#ifndef AUDIO_FILTERING
    typedef uint8_t Filter_Audio;
#endif
