enum
{
    THEME_DEFAULT,
    THEME_LIGHT,
    THEME_DARK,
    THEME_HIGHCONTRAST
    
    // @TODO
    // THEME_XRESOURCE
};

int COLOUR_DROPDOWN_ACTIVE_BACKGROUND;
int COLOUR_DROPDOWN_ACTIVE_FOREGROUND;
int COLOUR_EDGE_ACTIVE;
int COLOUR_EDGE_HOVER;
int COLOUR_EDGE_NORMAL;
int COLOUR_GROUP_UNUSUAL;
int COLOUR_HIGHLIGHT_BACKGROUND;
int COLOUR_HIGHLIGHT_FOREGROUND;
int COLOUR_LIST_BACKGROUND;
int COLOUR_LIST_FOREGROUND_SECONDARY;
int COLOUR_LIST_FOREGROUND;
int COLOUR_LIST_HOVER_BACKGROUND;
int COLOUR_MAIN_ACTIONTEXT;
int COLOUR_MAIN_BACKGROUND_SECONDARY;
int COLOUR_MAIN_BACKGROUND;
int COLOUR_MAIN_FOREGROUND_SECONDARY;
int COLOUR_MAIN_FOREGROUND;
int COLOUR_MAIN_QUOTETEXT;
int COLOUR_MAIN_URLTEXT;
int COLOUR_MENU_ACTIVE_FOREGROUND;
int COLOUR_MENU_ACTIVE;
int COLOUR_MENU_BACKGROUND;
int COLOUR_MENU_FOREGROUND;
int COLOUR_MENU_HOVER;
int COLOUR_SELF_FOREGROUND;

void theme_load(char loadtheme);
