enum {
    THEME_DEFAULT,
    THEME_LIGHT,
    THEME_DARK,
    THEME_HIGHCONTRAST
    // @TODO
    // THEME_XRESOURCE
};

int COLOR_MAIN_BACKGROUND;
int COLOR_MAIN_TEXT;
int COLOR_MAIN_SUBTEXT;
int COLOR_MAIN_ACTIONTEXT;
int COLOR_MAIN_QUOTETEXT;
int COLOR_MAIN_URLTEXT;
int COLOR_MENU_BACKGROUND;
int COLOR_MENU_TEXT;
int COLOR_MENU_HOVER_BACKGROUND;
int COLOR_MENU_ACTIVE_BACKGROUND;
int COLOR_MENU_ACTIVE_TEXT;
int COLOR_LIST_BACKGROUND;
int COLOR_LIST_HOVER_BACKGROUND;
int COLOR_LIST_TEXT;
int COLOR_LIST_SUBTEXT;
int COLOR_SELECTION_BACKGROUND;
int COLOR_SELECTION_TEXT;
int COLOR_GROUP_UNUSUAL;
int COLOR_EDGE_NORMAL;
int COLOR_EDGE_ACTIVE;
int COLOR_EDGE_HOVER;
int COLOR_ACTIVEOPTION_BACKGROUND;
int COLOR_ACTIVEOPTION_TEXT;
int COLOR_STATUS_ONLINE;
int COLOR_STATUS_AWAY;
int COLOR_STATUS_BUSY;
int COLOR_BUTTON_SUCCESS_BACKGROUND;
int COLOR_BUTTON_WARNING_BACKGROUND;
int COLOR_BUTTON_DANGER_BACKGROUND;
int COLOR_BUTTON_DISABLED_BACKGROUND;
int COLOR_BUTTON_SUCCESS_TEXT;
int COLOR_BUTTON_WARNING_TEXT;
int COLOR_BUTTON_DANGER_TEXT;
int COLOR_BUTTON_DISABLED_TEXT;
int COLOR_BUTTON_SUCCESS_HOVER_BACKGROUND;
int COLOR_BUTTON_WARNING_HOVER_BACKGROUND;
int COLOR_BUTTON_DANGER_HOVER_BACKGROUND;
int COLOR_BUTTON_DISABLED_HOVER_BACKGROUND;
int COLOR_BUTTON_SUCCESS_HOVER_TEXT;
int COLOR_BUTTON_WARNING_HOVER_TEXT;
int COLOR_BUTTON_DANGER_HOVER_TEXT;
int COLOR_BUTTON_DISABLED_HOVER_TEXT;

void theme_load(char loadtheme);

uint32_t status_color[4];

char theme;
