.TH UTOX "1" "March 2015" "µTox 0.2n" "User Commands"
.SH NAME
µTox \- Lightweight Tox client

.SH SYNOPSIS
utox [OPTIONS]

.SH DESCRIPTION
µTox is a free software lighweight X.org graphical Tox client.

µTox can be used for:
 * 1-to-1 text IM
 * group IM
 * audio calls
 * audio conversations
 * file transfer
 * avatar image support
 * video support

.SH OPTIONS
.SS General Options
  \-\-version      print version and exit
  \-\-portable     run in portable mode

.SH CONTRIBUTORS
Please see the list page:
.I https://github.com/notsecure/uTox/graphs/contributors

.SH BUGS
Please report bugs on
.I https://github.com/notsecure/uTox/issues

The website for
.B µTox
can be found at
.I http://utox.org/
and source code can be found at
.I https://github.com/notsecure/uTox
