.TH UTOX "1" "March 2015" "µTox 0.2n" "User Commands"
.SH NAME
µTox \- Lightweight Tox client

.SH SYNOPSIS
uasge: utox [--portable] [--theme <default|dark|light>]
   or: utox --version

.SH DESCRIPTION
µTox is a free software lighweight X.org graphical Tox client.

µTox can be used for:
 * 1-to-1 text IM
 * group IM
 * audio calls
 * video calls
 * group audio calls
 * desktop sharing
 * file transfer

.SH OPTIONS
.SS General Options
\-\-theme <THEME>
    Choose a colour scheme. Possible options are \fBdefault\fP, \fBdark\fP or \fBlight\fP.

\-\-portable
    run in portable mode

\-\-version
    print version and exit

.SH FILES
All files listed below are located in \fB$HOME/.config/tox\fP. If µTox is
running in portable mode, their location will be \fB./tox\fP.
.SS tox_save.tox
\fBtox_save.tox\fP is the file that contains the public/private key pair, name,
status and contacts. It's compatible with other Tox clients.
.SS utox_save
\fButox_save\fP is µTox' binary config file, it contains settings such as
language, proxy options, DPI or logging.
.SS avatars
The \fBavatars\fP directory contains other contacts' avatars along with their
hashes. Avatars are named [public_key].png, avatar hashes are called
[public_key].hash.

.SH CONTRIBUTORS
Please see the list page:
.I https://github.com/notsecure/uTox/graphs/contributors

.SH BUGS
Please report bugs on
.I https://github.com/notsecure/uTox/issues

The website for
.B µTox
can be found at
.I http://utox.org/
and source code can be found at
.I https://github.com/notsecure/uTox
