/* Source http://standards.freedesktop.org/xembed-spec/xembed-spec-latest.html */
enum {
XEMBED_EMBEDDED_NOTIFY,
XEMBED_WINDOW_ACTIVATE,
XEMBED_WINDOW_DEACTIVATE,
XEMBED_REQUEST_FOCUS,
XEMBED_FOCUS_IN,
XEMBED_FOCUS_OUT,
XEMBED_FOCUS_NEXT,
XEMBED_FOCUS_PREV,
XEMBED_GRAB_KEY,
XEMBED_UNGRAB_KEY,
XEMBED_MODALITY_ON = 10,
XEMBED_MODALITY_OFF,
XEMBED_REGISTER_ACCELERATOR,
XEMBED_UNREGISTER_ACCELERATOR,
XEMBED_ACTIVATE_ACCELERATOR,
};
