.TH UTOX "1" "January 2017" "µTox 0.12.1"
.SH NAME
µTox \- Lightweight Tox client

.SH SYNOPSIS
usage: utox [--portable] [--theme <default|dark|light|highcontrast|zenburn|solarized-light|solarized-dark>] [--set=<start-on-boot|show-window|hide-window>]
   or: utox --version
   or: utox --help

.SH DESCRIPTION
µTox is a free software lighweight X.org graphical Tox client.

µTox can be used for:
 * 1-to-1 text IM
 * group IM
 * audio calls
 * video calls
 * group audio calls
 * desktop sharing
 * file transfers

.SH OPTIONS
.IP "\fB\-t\fP \fI<THEME>\fP or \fB\-\-theme\fP \fI<THEME>\fP"
Choose a color scheme. Possible options are \fIdefault\fP, \fIdark\fP,
\fIlight\fP, \fIhighcontrast\fP, \fIzenburn\fP, \fIsolarized-light\fP, or
\fIsolarized-dark\fP.

.IP "\fB\-p\fP or \fB\-\-portable\fP"
Run in portable mode. All data will be saved to the tox folder in the current working directory, see FILES for more details.

.IP "\fB\-s\fP \fI<OPTION>\fP or \fB\-\-set \fP\fI<OPTION>\fP"
Set an option. The available options are "start-on-boot", "show-window" and "hide-window".

.IP "\fB\-s\fP \fI<OPTION>\fP or \fB\-\-set \fP\fI<OPTION>\fP"
Unset an option. The available option is "start-on-boot".

.IP "\fB\-v\fP or \fB\-\-verbose\fP"
Increase debug output level. Multiple -v options increase the verbosity. The
maximum is 3.

.IP "\fB--silent\fP"
Set the verbosity level to 0, disable all debugging output.

.IP "\fB\-h\fP or \fB\-\-help\fP"
Print a short description of available options.

.IP "\fB\-\-version\fP"
Print the version and exit.

.SH CHAT COMMANDS
These commands can be used in the chat window.
.IP "\fB/alias\fP <alias>"
Sets selected friend's alias to <alias>. It will be displayed instead of that
friend's name.
.IP "\fB/invite\fP <name>"
Invites <name> to the current groupchat.
.IP "\fB/sendfile\fP <path>"
Sends a file located in <path> to the current friend.
.IP "\fB/topic\fP <topic>"
Changes current groupchat's name/topic to <topic>. This command can also be
used to edit the current topic by typing /topic and pressing the tab key.
.IP "\fB/me\fP <action>"
Sends an message/action in the format <name> <action>, for example: Tox User
says hi

.SH FILES
All files listed below are located in \fB$HOME/.config/tox\fP. If µTox is
running in portable mode, their location will be \fB./tox\fP.
.IP \fBtox_save.tox\fP
\fBtox_save.tox\fP is the file that contains the public/private key pair, name,
status and contacts. It's compatible with other Tox clients.
.IP \fButox_save\fP
\fButox_save\fP is µTox' binary config file, it contains settings such as
language, proxy options, DPI or logging.
.IP \fBavatars\fP
The \fBavatars\fP directory contains other contacts' avatars. Files are named
after contacts' public keys (the first 64 characters of the ID).
.IP \fBTox_Auto_Accept\fP
Default directory for auto-accepted files in portable mode.
.IP "\fB[public key].txt\fP"
Those are friends' chat logs. µTox supports only 1v1 chat logging for now.
.IP "\fB[public key].fmetadata\fP"
Friend metadata file, currently used for storing aliases.
.IP "\fB[public key][file number].ftoutfo\fP"
Current outgoing file transfers' state. Used for resuming transfers across
client restarts.

.SH CONTRIBUTORS
Please see the list page:
.I https://github.com/uTox/uTox/graphs/contributors

.SH BUGS
Please report bugs on
.I https://github.com/uTox/uTox/issues

The website for
.B µTox
can be found at
.I http://utox.io/
and source code can be found at
.I https://github.com/uTox/uTox
